### ISSUE TITLE
Almost done

### ISSUE THREAD

**Issue by jacklametta** [domenicoCappello/Byob_client#4]
- [x] Textarea -> textField
- [x] Button push
- [x] Button pull
- [x] Push sposta da TextField a TextArea
- [x] Pull rimuove da TextArea e invia su TextField
- [x] dividere TextField per min e max + funzionamento checkbox fisso-variabile
- [x] extractDataFromTextArea in conf.txt
- [x] codice sleep condition
- [x] proxy port
- [x] settare default per checkboxes della SleepCondition

---
- [x] convenzione in lettura

**Comment by domenicoCappello** [comment]
Meglio prevedere la possibilita' di utilizzare un proxy diverso per ogni contatto -> proxy NON va spostato sotto

**Comment by domenicoCappello** [comment]
Da aggiungere campo proxyPort alla GUI!

**Comment by domenicoCappello** [comment]
Perche' idBot e' in URLDetails?

**Comment by jacklametta** [comment]
idBot, non so.

**Comment by jacklametta** [comment]
Codici sleep condition:
"E" Even Days
"O" Odd Days
"D" All Days
"A" AM
"P" PM
"H" 24 hours
