### ISSUE TITLE
Alessio's issues

### ISSUE THREAD

**Issue by jacklametta** [domenicoCappello/Byob_client#5]
Alessio
- [x] Fix MaskFormatter
- [x] Fix enable help
- [x] Spostare proxy sotto
- [x] salvare proxy all'inizio del file come "$" + hostname : port
- [x] mettere tasto launch
- [x] save .txt può annullarsi
- [x] fix default delle checkbox
- [x] default nella textarea
- [x] blocca testo nelle textarea dove vanno inseriti solo numeri
- [x] no default per proxy

---

Domenico
- [x] convenzione in lettura per proxy
- [x] testare proxy
- [x] Implementare tasto "Launch"
- [x] creare funzione di controllo dell'IP e che la porta sia [1025, 65535] che restituisca in caso di fallimento qualcosa di default

**Comment by jacklametta** [comment]
proxy è settato di default nel caso non venga inserito.
Aggiungere una checkbox per inserirlo o meno OPPURE inserirlo a prescindere?

**Comment by domenicoCappello** [comment]
Se non indicato nel file di configurazione (mediante la prima riga $ip_proxy:port_proxy), non viene settato nessun proxy e tutto continua a funzionare come prima.
Quindi non c'e' necessita' che l'utente faccia nulla se non specificare un proxy qualora volesse usarlo

**Comment by domenicoCappello** [comment]
Che ne dici di una checkbox a lato nella gui per decidere se verificare la risposta al primo contatto di ogni url? Per verificare intendo aspettare la risposta del server e loggarla, cosi' se c'e' qualche problema nel contattare le url l'utente puo' accorgersene subito

**Comment by domenicoCappello** [comment]
Che ne dici di una checkbox a lato nella gui per decidere se verificare la risposta al primo contatto di ogni url? Per verificare intendo aspettare la risposta del server e loggarla, cosi' se c'e' qualche problema nel contattare le url l'utente puo' accorgersene subito. Puo' passare anche qualche secondo per ricevere la risposta se si utilizza un proxy intasato.

**Comment by jacklametta** [comment]
@domenicoCappello : per la checkbox si può fare, ma prima finirei bene questa e sistemerei il codice della GUI.

**Comment by jacklametta** [comment]
@domenicoCappello : c'erano problemi con la MaskFormatter. Con essa puoi specificare il tipo di carattere da inserire ma devi anche specificare QUANTI. 
Ecco perchè si cancellava: io ne avevo definiti 5.

**Comment by domenicoCappello** [comment]
@jacklametta : Launch fatto, non ho toccato altre parti della GUI per non incasinarti, il tasto va reso visibile nei momenti giusti e legge il file di configurazione specificato in fileConfPath (che va quindi aggiornato quando si salva un nuovo fileConf e quando ne viene caricato uno nuovo).

Create funzioni Boolean Tools.checkIPv4String(String) e Boolean Tools.checkPort(int), se l' "and" tra le due restituisce false allora il proxy inserito non e' valido. Il check e' fatto al momento del click sul tasto Save, in caso di errore viene aperto un diverso popup di errore con solo la voce OK di conferma.
Ho commentato il codice (GUI 665) non avendo a disposizione ip e porta.

**Comment by jacklametta** [comment]
@domenicoCappello : il check andrebbe fatto anche se clicco su launch e non su save, giusto?
Mi diresti quando devo rendere disponibile il tasto launch? Grazie.

**Comment by jacklametta** [comment]
@domenicoCappello : nel caso proxy non vada, restituiamo qualcosa di default? Oppure chiediamo se vogliono il default o meno?

**Comment by domenicoCappello** [comment]
> il check andrebbe fatto anche se clicco su launch e non su save, giusto? 

Il codice con il check e' gia' presente (anche se commentato) a riga 665 della classe GUI

> Mi diresti quando devo rendere disponibile il tasto launch? 
1. Se il radiobutton dell'upload confFile e' selezionato && l'utente ha selezionato un fileConf
2. Se il secondo radiobutton e' selezionato && il textbox del fileConf e' non vuoto. In questo caso dovremmo salvarne prima il contenuto in un fileConf temporaneo (l'utente l'ha voluto eseguire ma non salvare), sovrascrivendo il fileConf temporaneo precedente. In questo modo non affolliamo di fileConf non voluti la directory di progetto e sfruttiamo il codice attuale del Parser che andra' comunque a leggere un file di configurazione.

> nel caso proxy non vada, restituiamo qualcosa di default? Oppure chiediamo se vogliono il default o meno?

In che senso non va il proxy?
1. Se l'utente non inserisce stringhe ip e porta valide secondo me non dobbiamo fare niente se non far uscire il popup e non far salvare;
2. Se il proxy inserito non funziona invece per qualche motivo ce ne possiamo accorgere solo aspettando il messaggio di risposta (che puo' metterci precchio ad arrivare, ~secondi). Per questo avrebbe senso controllare almeno la prima volta che contattiamo ogni URL il messaggio di risposta restituito (da qui la mia proposta precedente per far scegliere all'utente se fare verifiche oppure no)

**Comment by jacklametta** [comment]
@domenicoCappello nel caso in IP mettano una lettera? Gestisci il tutto?
