### ISSUE TITLE
GUI Issues

### ISSUE THREAD

**Issue by domenicoCappello** [domenicoCappello/Byob_client#6]
- [x] Save popup deve potersi chiudere o annullare
- [x] Campo Max_time della GUI non mantiene le cifre digitate
- [x] Aggiungere controllo (min < max) Contact Time

**Comment by domenicoCappello** [comment]
- [x] Save button non salva il file di configurazione
- [x] Se non presente nella url, inserire "http://"

**Comment by jacklametta** [comment]
http aggiunto all'URL se manca.

**Comment by jacklametta** [comment]
fixato il saveButton.
Bug: errata indicizzazione dovuto dall'inserimento della prima riga del proxy e non più alla fine di ogni push.
